### ISSUE TITLE
Validate that the result of `assertThat` is used.

### ISSUE THREAD

**Issue by evant** [jzbrooks/assertk-lint#1]
Originally taken from https://github.com/willowtreeapps/assertk/issues/394, it would be good to validate that the result of `assertThat` is used. Looks like there may be official kotlin support for this in the [future](https://youtrack.jetbrains.com/issue/KT-12719), but in the meantime a linting tool would make a good place for this.

**Comment by jzbrooks** [comment]
Fixed in #2
