### ISSUE TITLE
kotlin.test assertions are not caught

### ISSUE THREAD

**Issue by rbpaynetelus** [jzbrooks/assertk-lint#6]
When using kotlin.test assertions, I don't get a lint warning or error:

```kotlin
import kotlin.test.assertTrue

assertTrue(true)
```

I'm using Kotlin 1.9.10.

Shouldn't this be caught?

**Comment by jzbrooks** [comment]
Yes. This package name is wrong.

https://github.com/jzbrooks/assertk-lint/blob/7a1879f5c9f09a344f8af9001cc87d8863430b47/checks/src/main/kotlin/com/jzbrooks/assertk/lint/checks/TestFrameworkAssertionDetector.kt#L31

**Comment by jzbrooks** [comment]
Thanks!
